AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'lib/vagrant-goodhosts/config.rb'

Naming/FileName:
    Enabled: false
Naming/AccessorMethodName:
    Enabled: false
Metrics/MethodLength:
    Enabled: false
Metrics/PerceivedComplexity:
    Enabled: false
Metrics/ModuleLength:
    Enabled: false
Metrics/CyclomaticComplexity:
    Enabled: false
Metrics/AbcSize:
    Enabled: false
Style/AndOr:
    Enabled: false
Style/FrozenStringLiteralComment:
    Enabled: false
Style/RaiseArgs:
    Enabled: false
Layout/LineLength:
    Enabled: false
Style/StringLiterals:
    Enabled: false
Style/ExpandPathArguments:
    Enabled: false
Style/RedundantReturn:
    Enabled: false
Style/SymbolArray:
    Enabled: false
Style/ClassVars:
    Enabled: false
Style/YodaCondition:
    Enabled: false
Style/MethodCallWithoutArgsParentheses:
    Enabled: false
Style/NumericPredicate:
    Enabled: false
Style/ParallelAssignment:
    Enabled: false
Style/Not:
    Enabled: false
Style/EmptyLiteral:
    Enabled: false
Style/IfUnlessModifier:
    Enabled: false
Style/MutableConstant:
    Enabled: false
Style/SymbolLiteral:
    Enabled: false
Style/AccessorGrouping:
    Enabled: false
Style/Next:
    Enabled: false
Style/MultipleComparison:
    Enabled: false
Style/FormatStringToken:
    Enabled: false
Style/SoleNestedConditional:
    Enabled: false
Style/GuardClause:
    Enabled: false
Gemspec/RequiredRubyVersion:
    Enabled: false
